
import com.sun.jdi.connect.spi.Connection;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Neighas
 */
public class PenaltyPanel extends javax.swing.JPanel {

    private int penaltyAmount;
    private int bookID; 
    private String studentID; 
    private BookReturningPanel bookReturningPanel;
    private int amountPaid;
    private final JPanel panel_content;
    
  
    public PenaltyPanel(JPanel panel_content, int penaltyAmount, int bookID, String studentID, BookReturningPanel bookReturningPanel) {
        this.penaltyAmount = penaltyAmount;
        this.bookID = bookID; 
        this.studentID = studentID;
        this.bookReturningPanel = bookReturningPanel;
        
        initComponents();
        setPenaltyAmount(penaltyAmount);
        
        
        this.panel_content = panel_content;
        
        
        
        amount_paid.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) {
            updateChange();
        }
        public void removeUpdate(DocumentEvent e) {
            updateChange();
        }
        public void changedUpdate(DocumentEvent e) {
            updateChange();
        }
       
        
        
        });
        
        
        
        
        
        
        
        
        
        
        
    }
    
    
    // Setter method for amount_due
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amount_paid = new javax.swing.JTextField();
        cancel_btn = new javax.swing.JLabel();
        confirm_btn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        amount_due = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        amount_change = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(588, 471));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Amount Due:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Amount Paid:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Change:");

        amount_paid.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        amount_paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_paidActionPerformed(evt);
            }
        });

        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lastnato/cancel-btnn.png"))); // NOI18N
        cancel_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel_btnMouseExited(evt);
            }
        });

        confirm_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lastnato/confirm-btnn.png"))); // NOI18N
        confirm_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirm_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirm_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirm_btnMouseExited(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        amount_due.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amount_due.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                amount_dueInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(amount_due, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amount_due, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        amount_change.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amount_change.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                amount_changeInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(amount_change, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(amount_change, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amount_paid, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(cancel_btn)
                        .addGap(28, 28, 28)
                        .addComponent(confirm_btn)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amount_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel_btn)
                    .addComponent(confirm_btn))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 350));
    }// </editor-fold>//GEN-END:initComponents

    //methods
    
    
    
    
    
    
    
    public int getAmountPaid() {
        return amountPaid;
    }
    
    private void updateChange() {
        try {
            int amountPaid = Integer.parseInt(amount_paid.getText());
            if (amountPaid >= penaltyAmount) {
                int change = amountPaid - penaltyAmount;
                amount_change.setText(change + " Pesos");
            } else {
                amount_change.setText("");
            }
        } catch (NumberFormatException ex) {
            amount_change.setText("Please enter a valid number");
        }
    }
    
    
    
    
    
   private void setPenaltyAmount(int penaltyAmount) {
        amount_due.setText(penaltyAmount + " pesos");
    }
    
    
    private void updateDatabase(int bookID, String studentID) {
        // Implement your database update logic here
        // This is just a placeholder method, replace it with your actual implementation
        System.out.println("Updating database for bookID: " + bookID + ", studentID: " + studentID);
    }
    
    
    
    private void calculateChange() {
        try {
            int amountPaid = Integer.parseInt(amount_paid.getText());
            if (amountPaid < penaltyAmount) {
                JOptionPane.showMessageDialog(this, "invalid amount.");
            } else {
                int change = amountPaid - penaltyAmount;
                amount_change.setText(change + " Pesos");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "");
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void amount_paidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_paidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_paidActionPerformed

    private void cancel_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_btnMouseClicked
        // TODO add your handling code here:
        setVisible(false);

        // Hide the booklist_content JPanel
        JPanel parent = (JPanel) this.getParent();
        parent.setVisible(false);
    }//GEN-LAST:event_cancel_btnMouseClicked

    private void cancel_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_btnMouseEntered
        // TODO add your handling code here:
        cancel_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cancel_btnMouseEntered

    private void cancel_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_btnMouseExited
        // TODO add your handling code here:
        cancel_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cancel_btnMouseExited

    private void confirm_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirm_btnMouseClicked
        // TODO add your handling code here:
        int amountPaid;
        try {
            amountPaid = Integer.parseInt(amount_paid.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number.");
            return;
        }

        if (amountPaid >= penaltyAmount) {
            bookReturningPanel.updateDatabase(bookID, studentID, amountPaid); // Call updateDatabase from BookReturningPanel
            
            this.setVisible(false);
            JPanel parent = (JPanel) this.getParent();
             parent.setVisible(false);
             
             panel_content.removeAll();
             PaymentAcceptedPanel paymentAcceptedPanel = new PaymentAcceptedPanel(panel_content);

                        // Add WhosBorrowingPanel to panel_content JPanel
                        panel_content.add(paymentAcceptedPanel);

                        // Make panel_content JPanel visible
                        panel_content.setVisible(true);

                        // Repaint and revalidate panel_content JPanel
                        panel_content.revalidate();
                        panel_content.repaint();
             
             bookReturningPanel.clearFields();
             
             
             
        } else {
            JOptionPane.showMessageDialog(this, "Amount paid does not match or is less than the amount due. Please enter the correct amount.");
        }
    
        
           
    
    }//GEN-LAST:event_confirm_btnMouseClicked

    private void confirm_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirm_btnMouseEntered
        // TODO add your handling code here:
        confirm_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_confirm_btnMouseEntered

    private void confirm_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirm_btnMouseExited
        // TODO add your handling code here:
        confirm_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_confirm_btnMouseExited

    private void amount_dueInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_amount_dueInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_dueInputMethodTextChanged

    private void amount_changeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_amount_changeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_changeInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount_change;
    private javax.swing.JLabel amount_due;
    private javax.swing.JTextField amount_paid;
    private javax.swing.JLabel cancel_btn;
    private javax.swing.JLabel confirm_btn;
    private javax.swing.JLabel due_date1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
